apiVersion: apps/v1
kind: Deployment
metadata:
  name: cityfarm
spec:
  selector:
    matchLabels:
      app: cityfarm
  template:
    metadata:
      labels:
        app: cityfarm
    spec:
      containers:
      - name: cityfarm
        image: ayowilfred95/cityfarm:latest
        ports:
        - containerPort: 4000

---
apiVersion: v1
kind: Service
metadata:
  name: cityfarm-service
spec:
  type: LoadBalancer
  selector:
    app: cityfarm
  ports:
  - port: 80
    targetPort: 4000



