version: '3.1'
services:
  database:
    image: postgres:14
    container_name: nestjs-typeorm-database
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    restart: unless-stopped
    ports:
      - '5432:${DB_PORT}'
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
