apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: cityfarm-metrics
  name: cityfarm-metrics
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cityfarm-metrics
  template:
    metadata:
      labels:
        app: cityfarm-metrics
      annotations:
        prometheus.io/scrape: "true"
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
    spec:
      containers:
      - image: ayowilfred95/cityfarm:latest
        name: cityfarm
        ports:
        - containerPort: 4000
        env:
        - name: POSTGRES_NAME
          value: 'typeorm'
        - name: POSTGRES_PASSWORD
          value: 'typeorm'
        - name: POSTGRES_USER
          value: 'typeorm'
        - name: POSTGRES_HOST
          value: "192.168.64.9"
        - name: POSTGRES_PORT
          value: "30786"


