name: Build, Test, and Push Docker Image to Dockerhub

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Create .env file
        run: echo "${{ secrets.ENV_FILE }}" > .env

      - name: Start PostgreSQL service
        uses: docker://postgres:latest
        env:
          POSTGRES_DB: ${{ env.POSTGRES_NAME }}
          POSTGRES_USER: ${{ env.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ env.POSTGRES_PASSWORD }}
        with:
          ports:
            - "5432:5432"

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t ayowilfred95/cityfarm:latest .

      - name: Test application
        run: |
          docker run -d --name cityfarm-test \
            --env-file .env \
            -p 4000:4000 \
            ayowilfred95/cityfarm:latest
          docker logs -f cityfarm-test

      - name: Push Docker image
        run: docker push ayowilfred95/cityfarm:latest

      - name: Log out from Docker Hub
        run: docker logout
